(() => {
 const data={
  developer:{title:'Software developer',steps:[['Research','Perplexity','Current docs, APIs and external evidence'],['Architecture','Claude / ChatGPT','Reasoning, tradeoffs and design critique'],['Coding','Cursor','Implementation and codebase editing'],['Repo agent','Claude Code','Repo-wide or terminal tasks'],['Verification','Tests + human review','Compile, run, test, inspect diff and production risks'],['Automation','n8n','Operational glue where APIs/workflows justify it']]},
  qa:{title:'QA / test engineer',steps:[['Requirements','Claude / ChatGPT','Ambiguity, risks and missing acceptance criteria'],['Research','Perplexity','Current tool/docs discovery'],['Test design','ChatGPT / Claude','Cases, boundaries and failure-mode expansion'],['Automation','Cursor / Copilot','Implement maintainable automated checks'],['Evidence','NotebookLM','Ground analysis in requirements and test artifacts'],['Verification','Human + CI','Run tests, inspect false positives and validate coverage']]},
  researcher:{title:'Researcher / analyst',steps:[['Open web','Perplexity','Discover current public evidence'],['Closed sources','NotebookLM','Stay grounded in supplied documents'],['Synthesis','Claude','Compare evidence, conflicts and implications'],['Flexible drafting','ChatGPT','Transform verified findings into different outputs'],['Presentation','Gamma','Format an already-verified narrative'],['Verification','Human source check','Quote-check consequential claims']]},
  marketer:{title:'Marketing / content',steps:[['Research','Perplexity','Market, competitor and current evidence'],['Positioning','ChatGPT / Claude','Synthesize audience/problem/message'],['Images','Midjourney / ChatGPT Images','Visual concepts and assets'],['Presentation','Gamma','Campaign or client presentation output'],['Automation','n8n','Distribution and reporting workflows'],['Verification','Human brand/claim review','Check facts, promises, rights and brand fidelity']]},
  product:{title:'Product / project manager',steps:[['Source grounding','NotebookLM','PRDs, research and meeting source sets'],['Synthesis','Claude','Themes, requirements and tradeoffs'],['External research','Perplexity','Current market/product evidence'],['Planning','ChatGPT','Structured drafts, scenarios and action plans'],['Presentation','Gamma','Decision narratives and stakeholder decks'],['Verification','Human ownership','Owners, deadlines and product intent stay human-authoritative']]},
  business:{title:'Small business / operator',steps:[['General work','ChatGPT','Writing, analysis, planning and repeatable tasks'],['Research','Perplexity','Current suppliers, market and public information'],['Google work','Gemini','Optional when Google ecosystem integration matters'],['Presentation','Gamma','Fast proposals and presentation outputs'],['Automation','n8n / Make','Connect recurring operational workflows'],['Verification','Human approval','Money, customers, legal and external commitments require review']]}
 };
 const root=document.getElementById('roleStack');
 function render(k){const d=data[k];root.innerHTML='<div class="hub-section-heading"><div><span class="section-kicker">Default operating stack</span><h2>'+d.title+'</h2></div></div><div class="role-map">'+d.steps.map((s,i)=>'<div><span>'+String(i+1).padStart(2,'0')+'</span><strong>'+s[0]+'</strong><b>'+s[1]+'</b><p>'+s[2]+'</p></div>').join('')+'</div>';}
 document.querySelectorAll('#roleTabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#roleTabs button').forEach(x=>x.classList.toggle('active',x===b));render(b.dataset.role);window.dainTrack?.('role_stack_view',{role:b.dataset.role});});
 render('developer');
})();