const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
function builder(values){
 const elements={};
 const document={getElementById(id){return elements[id]??=( {value:values[id]||'',textContent:'',addEventListener(event,fn){this[event]=fn},scrollIntoView(){}})},querySelectorAll(){return []},querySelector(){return null}};
 vm.runInNewContext(fs.readFileSync('prompt-builder.js','utf8'),{document,window:{}});
 elements.promptBuilderForm.submit({preventDefault(){}});
 return elements.pbOutput.textContent;
}
test('worked examples are generated by the real Prompt Builder',()=>{
 for(const type of ['research','coding']){
  const goal=type==='research'?'Summarize the supplied PDFs for a purchasing decision':'Build an accessible contact form';
  const out=builder({pbType:type,pbGoal:goal,pbConstraints:'Do not invent missing information.'});
  assert.ok(out.includes(goal));assert.ok(out.includes('Do not invent missing information.'));
  assert.ok(out.includes(type==='research'?'Preserve a source':'test that should fail'));
 }
});
test('feedback analytics await HTTP success, remove task text and mark internal traffic',async()=>{
 const values=new Map([['dain_traffic','internal']]);const payloads=[];let ok=true;
 const storage={getItem:k=>values.get(k),setItem:(k,v)=>values.set(k,v)};
 const window={localStorage:storage,sessionStorage:storage};
 const context={window,localStorage:storage,sessionStorage:storage,crypto:{randomUUID:()=> 'id'},navigator:{userAgent:'test',language:'en'},location:{search:'',pathname:'/',hostname:'example.com'},document:{referrer:'',title:'Test',addEventListener(){}},URL,URLSearchParams,setTimeout(){},addEventListener(){},fetch:async(u,r)=>{payloads.push(JSON.parse(r.body));return {ok}}};
 vm.runInNewContext(fs.readFileSync('analytics.js','utf8'),context);
 assert.equal(await window.dainTrack('utility_feedback_detail',{outcome:'worked',goal:'SECRET',intent:'SECRET',query:'SECRET'}),true);
 const p=payloads.at(-1).properties;assert.equal(p.traffic_class,'internal');assert.equal(p.outcome,'worked');assert.equal(p.source,'direct');assert.ok(!JSON.stringify(p).includes('SECRET'));
 ok=false;assert.equal(await window.dainTrack('utility_feedback_detail',{}),false);
});
test('blocked browser storage does not stop analytics',()=>{
 const storage={getItem(){throw Error()},setItem(){throw Error()}};
 const window={localStorage:storage,sessionStorage:storage};
 assert.doesNotThrow(()=>vm.runInNewContext(fs.readFileSync('analytics.js','utf8'),{window,crypto:{randomUUID:()=> 'id'},navigator:{userAgent:'test'},location:{search:'',pathname:'/',hostname:'example.com'},document:{referrer:'',title:'Test',addEventListener(){}},URL,URLSearchParams,setTimeout(){},addEventListener(){},fetch:async()=>({ok:true})}));
});
module.exports={builder};
function taskPage(path,values={},saved={},disabled=false){
 const state=new Map([['dain_task_context_v1',JSON.stringify(saved)]]);if(disabled)state.set('dain_task_context_v1_disabled','1');
 const elements=Object.fromEntries(Object.entries(values).map(([id,value])=>[id,{value,tagName:'TEXTAREA',dispatchEvent(){}}]));
 const status={textContent:''},opt={checked:true},button={};const handlers={};
 const bar={querySelector:s=>s==='input'?opt:s==='button'?button:status};
 const document={getElementById:id=>elements[id]||null,createElement:()=>bar,querySelector:()=>({append(){}}),addEventListener:(e,fn)=>handlers[e]=fn};
 const sessionStorage={getItem:k=>state.get(k)||null,setItem:(k,v)=>state.set(k,v),removeItem:k=>state.delete(k)};
 vm.runInNewContext(fs.readFileSync('task-context.js','utf8'),{document,sessionStorage,location:{pathname:path},Event:function(){}});
 return {state,elements,status,opt,button,handlers};
}
test('task continues into builder, clear persists opt-out and existing text wins',()=>{
 const saved={version:1,goal:'Research solar panels',constraints:'Use primary sources'};
 const page=taskPage('/prompt-builder/',{pbGoal:'',pbConstraints:''},saved);
 assert.equal(page.elements.pbGoal.value,saved.goal);assert.equal(page.elements.pbConstraints.value,saved.constraints);
 page.button.onclick();page.handlers.submit();assert.equal(page.state.has('dain_task_context_v1'),false);assert.equal(page.opt.checked,false);
 const existing=taskPage('/prompt-builder/',{pbGoal:'A new task',pbConstraints:'My restrictions'},saved);
 assert.equal(existing.elements.pbGoal.value,'A new task');
 const optedOut=taskPage('/tool-finder/',{requirement:'Do something'},{},true);optedOut.handlers.submit();assert.equal(optedOut.state.get('dain_task_context_v1'),'{}');
});
test('result source and output are never captured into shared task storage',()=>{
 const saved={version:1,goal:'Original task',constraints:'No invented sources'};
 const page=taskPage('/verify-ai-output/',{ovSource:'Private source document',ovOutput:'Private result'},saved);
 page.handlers.submit();assert.equal(JSON.parse(page.state.get('dain_task_context_v1')).goal,'Original task');assert.ok(!page.state.get('dain_task_context_v1').includes('Private'));
});
test('affiliate links require approval, preserve normal links, and display disclosure',async()=>{
 const link={href:'https://vendor.example/',dataset:{},append(node){this.note=node.textContent}};
 const run=async partners=>{
  vm.runInNewContext(fs.readFileSync('affiliate-links.js','utf8'),{fetch:async()=>({ok:true,json:async()=>({partners})}),URL,document:{querySelectorAll:()=>[link],createElement:()=>({}),body:{}},MutationObserver:class{observe(){}}});
  await new Promise(resolve=>setImmediate(resolve));
 };
 await run([]);assert.equal(link.href,'https://vendor.example/');
 const partner={tool:'vendor',destination:'https://vendor.example/',affiliate_url:'https://vendor.example/?ref=approved',disclosure:'We may earn a commission.'};
 await run([partner]);assert.equal(link.href,partner.destination);
 await run([{...partner,approved:true}]);assert.equal(link.href,partner.affiliate_url);assert.equal(link.note,partner.disclosure);assert.equal(link.dataset.event,'affiliate_click');assert.ok(link.rel.includes('sponsored'));
});
